codecov:
  branch: dev

coverage:
  status:
    project:
      default:
        # minimum coverage ratio that the commit must meet to be considered a success
        target: 40%
        if_ci_failed: error
        only_pulls: true
    patch:
      default:
        # minimum coverage ratio that the commit must meet to be considered a success
        # XXX: this value should return to 70% after this PR is merged
        target: 40%
        if_ci_failed: error
        only_pulls: true

github_checks:
  annotations: true
