name: integration-test
on:
  push:
    branches:
      - master
      - release
      - release-candidate
    tags:
      - v*
  pull_request:
    branches:
      - release
      - release-candidate
      - master
      - test/void-tx-utxos

env:
  TEST_WALLET_START_TIMEOUT: '180000' # 3 minutes

jobs:
  itest:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 40

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v4.1.7
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node/releases/tag/v4.0.2
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm run test_integration

      - name: Upload debug transaction logs
        if: always()
        # https://github.com/actions/upload-artifact/releases/tag/v4.3.6
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a
        with:
          name: test-transaction-logs-${{ matrix.node-version }}
          path: tmp

      - name: Upload coverage
        if: ${{ matrix.node-version == '22.x' }}
        # https://github.com/codecov/codecov-action/releases/tag/v4.5.0
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Collect docker logs on failure
        if: failure()
        # https://github.com/jwalton/gh-docker-logs/releases/tag/v2.2.1
        uses: jwalton/gh-docker-logs@59c9656cd3cb7542525f3dce7ae2f44c0ff85d66
        with:
          dest: ./docker-logs-${{ matrix.node-version }}

      - name: Tar logs
        if: failure()
        run: tar cvzf ./docker-logs-${{ matrix.node-version }}.tgz ./docker-logs-${{ matrix.node-version }}

      - name: Upload logs to GitHub
        if: failure()
        # https://github.com/actions/upload-artifact/releases/tag/v4.3.6
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a
        with:
          name: logs-${{ matrix.node-version }}.tgz
          path: ./docker-logs-${{ matrix.node-version }}.tgz
