name: integration-test
on:
  pull_request:
    branches:
      - release
      - release-candidate
      - master

env:
  TEST_WALLET_START_TIMEOUT: '180000' # 3 minutes

jobs:
  itest:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 40

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v4.1.7
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node/releases/tag/v4.0.2
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm run test_integration

      - name: Upload debug transaction logs
        if: always()
        # https://github.com/actions/upload-artifact/releases/tag/v3.1.2
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: test-transacion-logs
          path: tmp

      - name: Upload coverage
        # https://github.com/codecov/codecov-action/releases/tag/v4.5.0
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Collect docker logs on failure
        if: failure()
        # https://github.com/jwalton/gh-docker-logs/releases/tag/v2.2.1
        uses: jwalton/gh-docker-logs@59c9656cd3cb7542525f3dce7ae2f44c0ff85d66
        with:
          dest: './docker-logs'

      - name: Tar logs
        if: failure()
        run: tar cvzf ./docker-logs.tgz ./docker-logs

      - name: Upload logs to GitHub
        if: failure()
        # https://github.com/actions/upload-artifact/releases/tag/v3.1.2
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: logs.tgz
          path: ./docker-logs.tgz
