name: tests
on:
  push:
    branches:
    - master
    - dev
    tags:
    - v*
  pull_request:
    branches:
    - dev
    - master
jobs:
  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 40  # default is 360
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      # https://github.com/actions/checkout/releases/tag/v3.5.0
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/actions/setup-node/releases/tag/v3.6.0
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Upload coverage
      # https://github.com/codecov/codecov-action/releases/tag/v4.3.0
      uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed
      if: ${{ matrix.node-version }} == 14.x
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        verbose: true
